pipelines:
  branches:
    master:
      - step:
          name: Deploy to S3 and CloudFront
          script:
            - pipe: atlassian/aws-s3-deploy:0.4.4
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: 'us-east-1'
                S3_BUCKET: $S3_BUCKET
                LOCAL_PATH: '.'
                EXTRA_ARGS: "--exclude=.git* --exclude=refresh.sh  --exclude=README.md --exclude=bitbucket-pipelines.yml"

            - pipe: atlassian/aws-cloudfront-invalidate:0.3.3
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: 'us-east-1'
                DISTRIBUTION_ID: $DISTRIBUTION_ID